"""initial_migration

Revision ID: 5bc14c8f89f6
Revises:
Create Date: 2026-01-12 15:14:18.053599

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5bc14c8f89f6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_requests_id"), table_name="requests")
    op.drop_table("requests")
    op.drop_index(op.f("ix_email_subscribers_email"), table_name="email_subscribers")
    op.drop_index(op.f("ix_email_subscribers_id"), table_name="email_subscribers")
    op.drop_table("email_subscribers")
    op.add_column(
        "items",
        sa.Column(
            "track",
            sa.Enum("INWARD", "OUTWARD", "RETURN", name="itemtrackstatus"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "track")
    op.create_table(
        "email_subscribers",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_date",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_sent_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("email_subscribers_pkey")),
    )
    op.create_index(
        op.f("ix_email_subscribers_id"), "email_subscribers", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_email_subscribers_email"), "email_subscribers", ["email"], unique=True
    )
    op.create_table(
        "requests",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "req_from", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("req_to", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "description", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_date",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "request_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_sent", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("requests_pkey")),
    )
    op.create_index(op.f("ix_requests_id"), "requests", ["id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("INWARD", "OUTWARD", "RETURN", name="transactiontype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("reason", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "storage_bin_rfid",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "transaction_date",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["storage_bin_rfid"],
            ["storage_bins.rfid"],
            name=op.f("transactions_storage_bin_rfid_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("transactions_pkey")),
        sa.UniqueConstraint(
            "storage_bin_rfid",
            "type",
            name=op.f("uq_rfid_transaction_type"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint(
            "username",
            name=op.f("users_username_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###
