"""changes migration

Revision ID: ca7b99c0ba17
Revises: d0f119d37f80
Create Date: 2025-12-04 15:47:12.835184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca7b99c0ba17'
down_revision: Union[str, Sequence[str], None] = 'd0f119d37f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_racks_id'), table_name='racks')
    op.drop_table('racks')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_rfid'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_requests_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_storage_bins_id'), table_name='storage_bins')
    op.drop_index(op.f('ix_storage_bins_rfid'), table_name='storage_bins')
    op.drop_table('storage_bins')
    op.drop_index(op.f('ix_request_items_id'), table_name='request_items')
    op.drop_table('request_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('request_items_item_id_fkey')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('request_items_request_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('request_items_pkey'))
    )
    op.create_index(op.f('ix_request_items_id'), 'request_items', ['id'], unique=False)
    op.create_table('storage_bins',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('storage_bins_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('rfid', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rack_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.rack_id'], name='storage_bins_rack_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='storage_bins_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_storage_bins_rfid'), 'storage_bins', ['rfid'], unique=True)
    op.create_index(op.f('ix_storage_bins_id'), 'storage_bins', ['id'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('req_from', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('req_to', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('request_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('requests_pkey'))
    )
    op.create_index(op.f('ix_requests_id'), 'requests', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('items_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('rfid', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rack_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('storage_bin_rfid', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.rack_id'], name='items_rack_id_fkey'),
    sa.ForeignKeyConstraint(['storage_bin_rfid'], ['storage_bins.rfid'], name='items_storage_bin_rfid_fkey'),
    sa.PrimaryKeyConstraint('id', name='items_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_items_rfid'), 'items', ['rfid'], unique=True)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_table('racks',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('racks_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('rack_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='racks_pkey'),
    sa.UniqueConstraint('rack_id', name='racks_rack_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_racks_id'), 'racks', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', postgresql.ENUM('INWARD', 'OUTWARD', 'RETURN', name='transactiontype'), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('transactions_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
